# Machine Learning November Minor Project
## create a classification model to predict whether price range of mobile based on certain specification

In [132]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt

In [133]:
df=pd.read_csv("MOBILE.csv")
df

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7   
1              1021     1          0.5         1   0       1          53   
2               563     1          0.5         1   2       1          41   
3               615     1          2.5         0   0       0          10   
4              1821     1          1.2         0  13       1          44   
...             ...   ...          ...       ...  ..     ...         ...   
1995            794     1          0.5         1   0       1           2   
1996           1965     1          2.6         1   0       0          39   
1997           1911     0          0.9         1   1       1          36   
1998           1512     0          0.9         0   4       1          46   
1999            510     1          2.0         1   5       1          45   

      m_dep  mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  \
0       0.6        188        2  ...         20       756  2549     9     7   
1       0.7        136        3  ...        905      1988  2631    17     3   
2       0.9        145        5  ...       1263      1716  2603    11     2   
3       0.8        131        6  ...       1216      1786  2769    16     8   
4       0.6        141        2  ...       1208      1212  1411     8     2   
...     ...        ...      ...  ...        ...       ...   ...   ...   ...   
1995    0.8        106        6  ...       1222      1890   668    13     4   
1996    0.2        187        4  ...        915      1965  2032    11    10   
1997    0.7        108        8  ...        868      1632  3057     9     1   
1998    0.1        145        5  ...        336       670   869    18    10   
1999    0.9        168        6  ...        483       754  3919    19     4   

      talk_time  three_g  touch_screen  wifi  price_range  
0            19        0             0     1            1  
1             7        1             1     0            2  
2             9        1             1     0            2  
3            11        1             0     0            2  
4            15        1             1     0            1  
...         ...      ...           ...   ...          ...  
1995         19        1             1     0            0  
1996         16        1             1     1            2  
1997          5        1             1     0            3  
1998         19        1             1     1            0  
1999          2        1             1     1            3  

[2000 rows x 21 columns]

In [134]:
df.head()

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  \
0            842     0          2.2         0   1       0           7    0.6   
1           1021     1          0.5         1   0       1          53    0.7   
2            563     1          0.5         1   2       1          41    0.9   
3            615     1          2.5         0   0       0          10    0.8   
4           1821     1          1.2         0  13       1          44    0.6   

   mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  talk_time  \
0        188        2  ...         20       756  2549     9     7         19   
1        136        3  ...        905      1988  2631    17     3          7   
2        145        5  ...       1263      1716  2603    11     2          9   
3        131        6  ...       1216      1786  2769    16     8         11   
4        141        2  ...       1208      1212  1411     8     2         15   

   three_g  touch_screen  wifi  price_range  
0        0             0     1            1  
1        1             1     0            2  
2        1             1     0            2  
3        1             0     0            2  
4        1             1     0            1  

[5 rows x 21 columns]

In [135]:
df.shape

(2000, 21)

TARGET VARIABLE

In [136]:
df['price_range'].value_counts()

1    500
2    500
3    500
0    500
Name: price_range, dtype: int64

# 1) REMOVE HANDLE NULL VALUES(IF ANY)


In [137]:
df.isnull().sum()

battery_power    0
blue             0
clock_speed      0
dual_sim         0
fc               0
four_g           0
int_memory       0
m_dep            0
mobile_wt        0
n_cores          0
pc               0
px_height        0
px_width         0
ram              0
sc_h             0
sc_w             0
talk_time        0
three_g          0
touch_screen     0
wifi             0
price_range      0
dtype: int64

HANDLING DUPLICATES

In [138]:
df.duplicated().sum()

0

In [139]:
df.drop_duplicates(inplace=True)

In [140]:
df.duplicated().sum()

0

CHECKING DATATYPES

In [141]:
df.dtypes

battery_power      int64
blue               int64
clock_speed      float64
dual_sim           int64
fc                 int64
four_g             int64
int_memory         int64
m_dep            float64
mobile_wt          int64
n_cores            int64
pc                 int64
px_height          int64
px_width           int64
ram                int64
sc_h               int64
sc_w               int64
talk_time          int64
three_g            int64
touch_screen       int64
wifi               int64
price_range        int64
dtype: object

#selecting dependent(x) and independent(y) variables

In [142]:
x=df.drop('price_range',axis=1)
y=df['price_range']
print(type(x))
print(type(y))
print(x.shape)
print(y.shape)

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>
(2000, 20)
(2000,)


x=df.drop('price_range',axis=1)
y=df['price_range']
print(type(x))
print(type(y))
print(x.shape)
print(y.shape)
#x-tarin , y_train

# #2) spliting data into training and test data

In [143]:
from sklearn.model_selection import train_test_split

In [144]:
print(2000*0.25)

500.0


In [145]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=42)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape) 

(1500, 20)
(500, 20)
(1500,)
(500,)


### CONFUSION MATRIX

In [146]:
from sklearn.metrics import confusion_matrix,classification_report


In [147]:
def eval_model(ytest,ypred):
    cm=confusion_matrix(ytest,ypred)
    print(cm)
    print(classification_report(ytest,ypred))
def nscore(model):
    print('training score', model.score(x_train,y_train))
    print('testing score',model.score(x_test,y_test))

# #3 Apply the following models on the training dataset and generate the predicted value for the test dataset

# (a) LOGISTIC REGRESSION



In [148]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [149]:
from sklearn.linear_model import LogisticRegression  

In [150]:
 #applying linear regression
m1=LogisticRegression(max_iter=10000,solver="liblinear")
m1.fit(x_train,y_train)

LogisticRegression(max_iter=10000, solver='liblinear')

In [151]:
#Accuracy
print('train score',m1.score(x_train,y_train))
print('train score',m1.score(x_test,y_test))

train score 0.7946666666666666
train score 0.782


In [152]:
nscore(m1)

training score 0.7946666666666666
testing score 0.782


In [153]:
ypred_m1=m1.predict(x_test)
print(ypred_m1)

[0 2 0 3 1 2 2 0 3 1 0 1 1 3 3 2 3 3 1 0 0 1 2 2 0 2 3 3 2 0 0 0 3 0 2 1 2
 0 3 0 2 3 3 0 2 3 1 1 3 1 3 1 0 0 1 2 2 3 0 0 1 3 3 2 1 0 3 3 2 2 2 1 0 1
 3 0 1 3 1 1 3 1 2 0 1 3 2 3 3 0 3 3 2 1 3 2 2 3 2 1 0 0 1 0 0 3 2 0 2 1 0
 0 3 1 3 2 3 3 0 2 1 3 3 2 3 3 0 3 0 2 3 0 1 3 0 3 1 0 0 2 3 1 3 3 0 0 0 2
 2 2 3 1 1 0 2 3 0 1 0 1 2 3 3 1 1 0 0 2 2 3 3 0 0 0 3 1 2 2 1 0 0 0 0 0 3
 2 0 3 0 0 0 0 1 3 3 1 0 1 2 0 1 2 1 3 3 3 1 2 0 0 0 1 1 1 3 1 1 2 1 1 3 1
 3 0 0 2 0 3 0 0 1 0 1 3 2 1 1 2 3 0 2 3 2 3 0 3 1 3 3 3 2 1 0 3 3 1 3 3 3
 3 3 0 1 2 3 2 3 0 2 3 2 3 2 0 0 2 0 3 3 1 3 2 0 3 1 2 0 0 3 0 1 2 3 3 3 0
 1 0 0 3 3 0 1 2 2 0 3 3 2 3 1 3 3 0 2 1 2 2 0 0 0 3 3 3 1 0 1 0 2 3 2 0 2
 3 2 1 3 0 0 3 1 3 1 0 1 1 2 1 2 3 1 0 1 2 3 0 3 0 0 1 0 2 2 2 2 3 0 3 2 3
 3 3 3 3 1 2 0 3 2 3 3 0 2 3 1 3 3 3 1 0 2 3 0 0 2 3 2 1 2 2 1 3 0 3 1 3 0
 0 1 0 1 0 2 0 2 3 3 1 2 1 3 1 1 3 1 0 0 3 0 2 0 0 2 3 3 0 2 0 1 2 3 3 0 3
 0 2 0 0 3 3 0 2 1 2 3 2 1 0 1 3 1 0 3 1 0 0 3 2 3 2 0 3 2 0 1 2 3 2 1 0 0
 0 2 3 1 0 2 3 1 3 1 2 2 

In [154]:
ypred_m1=m1.predict(x_test)
eval_model(y_test,ypred_m1)

[[124   7   1   0]
 [ 13  72  33   0]
 [  0  25  69  26]
 [  0   0   4 126]]
              precision    recall  f1-score   support

           0       0.91      0.94      0.92       132
           1       0.69      0.61      0.65       118
           2       0.64      0.57      0.61       120
           3       0.83      0.97      0.89       130

    accuracy                           0.78       500
   macro avg       0.77      0.77      0.77       500
weighted avg       0.77      0.78      0.77       500



In [155]:
from sklearn.metrics import confusion_matrix,classification_report

In [156]:
print(confusion_matrix(y_test,ypred_m1))
print(classification_report(y_test,ypred_m1))

[[124   7   1   0]
 [ 13  72  33   0]
 [  0  25  69  26]
 [  0   0   4 126]]
              precision    recall  f1-score   support

           0       0.91      0.94      0.92       132
           1       0.69      0.61      0.65       118
           2       0.64      0.57      0.61       120
           3       0.83      0.97      0.89       130

    accuracy                           0.78       500
   macro avg       0.77      0.77      0.77       500
weighted avg       0.77      0.78      0.77       500



In [157]:
print('train score',m1.score(x_test,y_test))

train score 0.782


# (b)KNN classification

In [158]:
from sklearn.neighbors import KNeighborsClassifier


In [159]:
m2=KNeighborsClassifier(n_neighbors=11)
m2.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=11)

In [160]:
#Accuracy
print('train score',m2.score(x_train,y_train))
print('train score',m2.score(x_test,y_test))

train score 0.952
train score 0.938


In [161]:
ypred_m2=m2.predict(x_test)
print(ypred_m2)

[0 2 1 3 1 1 2 0 3 1 0 1 2 3 2 2 3 3 1 0 0 1 1 2 0 1 3 2 2 0 0 0 3 0 1 1 2
 0 3 0 2 2 2 0 3 2 2 1 3 1 3 1 0 0 0 1 1 3 0 0 1 3 3 1 0 0 3 3 1 2 2 2 0 1
 2 0 0 3 2 1 3 2 1 0 1 3 1 3 3 0 3 3 2 1 3 2 2 3 1 1 0 0 1 0 0 3 2 0 1 1 0
 0 3 1 3 2 3 2 0 2 1 3 2 1 3 3 0 2 0 2 3 0 2 2 0 3 1 0 0 2 2 1 2 2 0 0 0 1
 1 2 3 1 1 0 2 2 0 1 0 2 2 3 3 2 1 0 1 2 2 3 3 0 1 0 3 1 1 2 1 0 0 0 0 0 3
 2 0 3 0 0 0 0 1 3 3 1 0 1 1 1 1 1 2 3 3 3 1 2 0 0 0 2 1 1 3 1 0 2 1 1 3 2
 3 0 0 2 1 3 0 1 2 0 2 3 2 0 1 3 3 0 1 3 2 3 0 3 1 2 3 3 2 1 1 3 3 1 3 3 3
 3 3 0 2 2 2 1 3 0 1 3 2 2 2 1 0 1 0 3 3 1 3 1 0 3 1 2 0 0 3 0 1 2 3 3 3 1
 1 0 1 3 3 0 1 2 2 0 3 3 2 3 2 3 2 0 2 1 1 1 0 0 0 3 2 3 1 0 1 0 1 2 3 0 3
 3 2 1 2 0 0 2 1 3 2 0 1 1 1 0 1 3 2 0 0 3 3 0 3 0 0 2 0 1 2 2 2 3 0 3 2 2
 3 3 3 2 1 1 0 3 1 3 3 0 2 3 2 3 3 3 0 0 2 3 0 0 2 3 2 1 1 2 1 2 1 3 1 2 0
 0 1 0 1 0 1 0 2 2 3 2 1 1 3 1 0 3 1 0 0 3 0 1 0 0 1 3 3 0 2 0 1 1 3 3 1 2
 0 2 0 0 3 3 0 2 2 1 3 1 2 0 1 3 1 0 3 1 0 0 3 2 3 2 0 2 1 0 1 2 3 2 1 1 0
 1 2 2 1 1 1 3 1 2 0 2 2 

In [162]:
from sklearn.metrics import confusion_matrix,classification_report

In [163]:
print(confusion_matrix(y_test,ypred_m2))
print(classification_report(y_test,ypred_m2))

[[127   5   0   0]
 [  4 113   1   0]
 [  0  11 106   3]
 [  0   0   7 123]]
              precision    recall  f1-score   support

           0       0.97      0.96      0.97       132
           1       0.88      0.96      0.91       118
           2       0.93      0.88      0.91       120
           3       0.98      0.95      0.96       130

    accuracy                           0.94       500
   macro avg       0.94      0.94      0.94       500
weighted avg       0.94      0.94      0.94       500



In [164]:
print('train score',m2.score(x_test,y_test))

train score 0.938


# # (c) SVM classifier with linear and rbf kernal


In [165]:
from sklearn.svm import SVC

In [166]:
m3=SVC(kernel='linear')


In [167]:
m3.fit(x_train,y_train)

SVC(kernel='linear')

In [168]:
nscore(m3)

training score 0.992
testing score 0.97


In [169]:
#Accuracy
print('train score',m3.score(x_train,y_train))
print('train score',m3.score(x_test,y_test))

train score 0.992
train score 0.97


In [170]:
ypred_m3=m3.predict(x_test)
print(ypred_m3)

[0 2 1 3 1 1 2 0 3 1 0 1 2 3 3 2 3 3 1 0 0 2 1 2 0 1 3 2 2 0 0 0 3 0 1 1 2
 0 3 0 2 3 2 0 3 3 2 1 3 1 3 1 0 0 1 1 1 3 0 0 1 3 3 1 0 0 3 3 1 2 2 2 0 1
 2 0 1 3 2 2 3 2 1 0 1 3 1 3 3 0 3 3 2 1 3 2 2 3 1 1 0 0 1 0 1 3 2 0 1 1 0
 0 3 1 3 2 3 2 0 2 1 3 2 1 3 3 0 2 0 2 3 0 2 2 0 3 1 0 0 2 2 1 2 2 0 0 0 1
 1 2 3 1 1 0 2 2 0 1 0 2 2 3 3 3 1 0 1 2 2 3 3 0 1 0 3 1 1 2 1 0 0 0 0 0 3
 2 0 3 0 0 0 0 1 3 3 1 0 1 1 1 1 2 2 3 3 3 1 2 0 0 0 2 1 1 3 1 1 2 1 1 3 2
 3 0 0 2 1 3 0 1 2 0 2 3 2 0 1 3 3 0 1 3 3 3 0 3 1 2 3 3 2 1 0 3 3 1 3 3 3
 3 3 0 1 2 2 2 3 0 2 3 2 2 2 1 0 2 0 3 3 1 3 1 1 3 1 2 0 0 3 0 1 2 3 3 3 1
 1 0 1 3 3 0 1 2 2 0 3 3 2 3 2 3 2 0 2 1 1 1 0 0 0 3 3 3 1 0 1 0 1 2 3 0 3
 3 2 1 3 0 0 2 1 3 2 0 1 1 1 1 1 3 2 0 0 3 3 0 3 0 0 2 0 1 2 2 2 3 0 3 2 3
 3 3 3 2 1 1 0 3 1 3 3 0 2 3 2 3 3 3 0 0 2 3 0 0 2 3 2 1 1 2 1 3 0 3 1 2 0
 0 1 0 1 0 1 0 2 2 3 2 1 1 2 1 1 3 1 0 0 3 0 1 0 0 2 3 3 0 2 0 1 1 3 3 1 2
 0 2 0 0 3 3 0 2 2 2 3 1 2 0 1 3 1 0 3 1 0 0 3 2 3 2 0 2 1 0 1 2 3 2 1 1 0
 1 2 2 1 0 1 3 1 2 0 2 2 

In [171]:
from sklearn.metrics import confusion_matrix,classification_report

In [172]:
print(confusion_matrix(y_test,ypred_m3))
print(classification_report(y_test,ypred_m3))

[[127   5   0   0]
 [  1 117   0   0]
 [  0   3 112   5]
 [  0   0   1 129]]
              precision    recall  f1-score   support

           0       0.99      0.96      0.98       132
           1       0.94      0.99      0.96       118
           2       0.99      0.93      0.96       120
           3       0.96      0.99      0.98       130

    accuracy                           0.97       500
   macro avg       0.97      0.97      0.97       500
weighted avg       0.97      0.97      0.97       500



In [173]:
print('train score',m3.score(x_test,y_test))

train score 0.97


# (d)Decision Tree Classifier



In [174]:
#(d)Decision Tree Classifier
from sklearn.tree import DecisionTreeClassifier


In [175]:
m4 = DecisionTreeClassifier(criterion='entropy',max_depth=5)
m4.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=5)

In [176]:
nscore(m4)

training score 0.8793333333333333
testing score 0.826


In [177]:
ypred_m4=m4.predict(x_test)
eval_model(y_test,ypred_m4)

[[121  11   0   0]
 [ 11  97  10   0]
 [  0  19  82  19]
 [  0   0  17 113]]
              precision    recall  f1-score   support

           0       0.92      0.92      0.92       132
           1       0.76      0.82      0.79       118
           2       0.75      0.68      0.72       120
           3       0.86      0.87      0.86       130

    accuracy                           0.83       500
   macro avg       0.82      0.82      0.82       500
weighted avg       0.83      0.83      0.83       500



In [178]:
#Accuracy
print('train score',m4.score(x_train,y_train))
print('train score',m4.score(x_test,y_test))

train score 0.8793333333333333
train score 0.826


In [179]:
ypred_m4=m4.predict(x_test)
print(ypred_m4)

[0 1 1 3 1 1 2 0 2 1 0 1 2 3 2 2 3 3 1 0 0 2 1 2 0 1 2 2 2 0 0 0 3 0 1 1 3
 0 3 0 1 3 2 0 2 2 2 1 3 1 3 1 0 0 1 1 1 2 0 0 0 3 3 1 0 0 3 3 1 2 1 2 0 1
 3 0 1 3 2 1 3 2 1 0 2 3 2 3 3 0 2 3 1 1 3 2 2 3 1 1 0 0 0 0 0 3 2 0 1 1 0
 0 2 1 2 2 2 3 0 2 1 3 1 1 3 3 0 3 0 2 3 0 2 2 0 2 1 0 0 2 3 1 3 3 0 0 0 1
 2 3 3 2 0 0 2 2 0 2 0 1 2 3 2 3 1 0 0 2 2 3 3 1 1 0 3 1 1 2 1 0 0 0 0 0 3
 2 0 3 0 0 0 0 1 3 2 2 0 0 1 1 1 2 2 2 3 3 1 2 0 0 0 2 1 1 3 1 1 2 1 1 3 2
 3 0 0 1 1 3 0 0 1 0 2 3 2 1 1 3 3 0 1 3 3 3 0 3 1 2 3 3 2 1 1 3 3 1 3 3 3
 3 3 0 1 2 3 1 3 0 1 3 2 2 2 1 0 1 0 2 3 1 3 1 0 3 1 2 0 0 3 0 1 2 3 3 3 1
 1 0 1 3 3 0 2 2 2 0 3 3 2 3 2 3 2 0 2 1 1 1 0 0 0 3 2 3 2 0 1 0 2 3 3 1 2
 3 2 1 3 0 0 3 1 3 2 0 1 1 1 0 1 3 1 0 0 3 3 0 3 0 0 2 0 1 2 2 2 3 0 3 2 2
 3 3 3 2 1 1 0 3 1 3 3 0 2 3 1 3 3 3 0 0 2 3 0 0 2 3 1 1 1 2 2 3 1 3 2 2 0
 1 1 0 1 0 1 0 2 2 3 2 1 1 3 1 1 3 1 0 0 3 0 1 0 0 1 3 3 0 2 0 1 1 3 3 0 3
 1 2 0 0 3 3 0 1 2 2 3 1 2 0 1 3 1 0 3 2 0 0 3 2 3 2 0 3 1 0 1 2 3 2 1 0 0
 1 2 1 1 1 1 3 1 2 0 3 3 

In [180]:
from sklearn.metrics import confusion_matrix,classification_report

In [181]:
print(confusion_matrix(y_test,ypred_m4))
print(classification_report(y_test,ypred_m4))

[[121  11   0   0]
 [ 11  97  10   0]
 [  0  19  82  19]
 [  0   0  17 113]]
              precision    recall  f1-score   support

           0       0.92      0.92      0.92       132
           1       0.76      0.82      0.79       118
           2       0.75      0.68      0.72       120
           3       0.86      0.87      0.86       130

    accuracy                           0.83       500
   macro avg       0.82      0.82      0.82       500
weighted avg       0.83      0.83      0.83       500



In [182]:
print('train score',m4.score(x_test,y_test))

train score 0.826


In [183]:
fn = x_train.columns
cn = ['0','1']
print(fn)
print(cn)

Index(['battery_power', 'blue', 'clock_speed', 'dual_sim', 'fc', 'four_g',
       'int_memory', 'm_dep', 'mobile_wt', 'n_cores', 'pc', 'px_height',
       'px_width', 'ram', 'sc_h', 'sc_w', 'talk_time', 'three_g',
       'touch_screen', 'wifi'],
      dtype='object')
['0', '1']


# (e)Random forest Classifier



In [184]:
from sklearn.ensemble import RandomForestClassifier

In [185]:
m5=RandomForestClassifier(n_estimators=80,criterion='entropy',max_depth=7)
m5.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy', max_depth=7, n_estimators=80)

In [186]:
nscore(m5)

training score 0.9713333333333334
testing score 0.874


In [187]:
ypred_m5=m5.predict(x_test)
eval_model(y_test,ypred_m5)

[[124   8   0   0]
 [ 10  97  11   0]
 [  0  14  89  17]
 [  0   0   3 127]]
              precision    recall  f1-score   support

           0       0.93      0.94      0.93       132
           1       0.82      0.82      0.82       118
           2       0.86      0.74      0.80       120
           3       0.88      0.98      0.93       130

    accuracy                           0.87       500
   macro avg       0.87      0.87      0.87       500
weighted avg       0.87      0.87      0.87       500



In [188]:
#Accuracy
print('train score',m5.score(x_train,y_train))
print('train score',m5.score(x_test,y_test))

train score 0.9713333333333334
train score 0.874


In [189]:
ypred_m5=m5.predict(x_test)
print(ypred_m5)

[0 2 1 3 1 2 2 0 3 1 0 1 2 3 3 2 3 3 1 0 0 1 1 2 0 1 3 2 2 0 0 0 3 0 1 1 3
 0 3 0 2 3 2 0 3 3 2 1 3 1 3 1 0 0 1 0 1 3 0 0 0 3 3 1 0 0 3 3 1 2 2 2 0 1
 3 0 0 3 2 2 3 2 1 0 1 3 2 3 3 0 3 3 2 1 3 2 2 3 2 1 0 0 1 0 0 3 2 0 1 1 0
 0 3 1 3 2 3 3 0 2 1 3 3 1 3 3 0 3 1 2 3 0 2 2 0 3 1 0 0 2 3 0 2 3 0 0 0 1
 2 2 3 1 1 0 2 2 0 1 0 2 2 3 3 3 1 0 0 2 2 3 3 1 1 0 3 1 1 2 1 0 0 0 0 0 3
 2 0 3 0 0 0 0 1 3 3 1 0 1 2 1 1 2 2 3 3 3 1 2 0 0 0 2 1 1 3 1 0 2 2 1 3 1
 3 0 0 2 1 3 0 0 1 0 1 3 2 0 1 3 3 0 1 3 3 3 0 3 1 2 3 3 3 1 1 3 3 1 3 3 3
 3 3 0 1 2 2 2 3 0 2 3 2 3 2 1 0 2 0 3 3 1 3 1 0 3 1 2 0 0 3 0 1 2 3 3 3 1
 1 0 1 3 3 0 1 1 2 0 3 3 2 3 1 3 2 0 2 1 2 1 0 0 0 3 3 3 1 0 1 1 2 2 2 0 3
 3 2 1 3 0 0 3 1 3 2 0 1 1 2 1 1 3 1 0 0 3 3 0 3 0 0 1 0 0 2 2 2 3 0 3 2 2
 3 3 3 2 1 2 0 3 2 3 3 0 2 3 2 3 3 3 0 0 2 3 0 0 2 3 1 1 1 2 1 2 0 3 1 2 0
 0 1 0 1 0 2 1 2 2 3 2 1 1 3 1 0 3 1 0 0 3 0 1 0 0 1 3 3 0 2 1 1 1 3 3 0 2
 0 2 0 0 3 3 0 2 2 1 3 1 1 0 1 3 1 0 3 1 0 0 3 2 3 2 0 2 0 0 1 2 3 2 1 1 0
 1 2 2 1 1 1 3 1 2 0 3 3 

In [190]:
from sklearn.metrics import confusion_matrix,classification_report

In [191]:
print(confusion_matrix(y_test,ypred_m5))
print(classification_report(y_test,ypred_m5))

[[124   8   0   0]
 [ 10  97  11   0]
 [  0  14  89  17]
 [  0   0   3 127]]
              precision    recall  f1-score   support

           0       0.93      0.94      0.93       132
           1       0.82      0.82      0.82       118
           2       0.86      0.74      0.80       120
           3       0.88      0.98      0.93       130

    accuracy                           0.87       500
   macro avg       0.87      0.87      0.87       500
weighted avg       0.87      0.87      0.87       500



In [192]:
print('train score',m5.score(x_test,y_test))

train score 0.874
